version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: cms_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_cms
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: cms_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: